In [1]:
import pandas as pd 
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
orders = pd.read_csv("/Users/abhijeetsinghparihar/Desktop/Projects/Supply Chain Project/CartIQ/data/processed/master_orders.csv")
transactions = (orders.groupby("order_id")["product_name"].apply(list).tolist())
te = TransactionEncoder()

In [3]:
orders

,order_id,order_dow,order_hour_of_day,days_since_prior_order,order_number,product_id,add_to_cart_order,reordered,product_name,department_id,department
0,1901567,1,10,3.0,3,47766,1,1,Organic Avocado,4,produce
1,1901567,1,10,3.0,3,32792,2,1,Chipotle Beef & Pork Realstick,19,snacks
2,1901567,1,10,3.0,3,20574,3,1,Roasted Turkey,20,deli
3,1901567,1,10,3.0,3,7781,4,0,Organic Sticks Low Moisture Part Skim Mozzarel...,16,dairy eggs
4,1901567,1,10,3.0,3,28874,5,0,Carrot Ginger Soup,20,deli
...,...,...,...,...,...,...,...,...,...,...,...
2019708,550836,2,13,9.0,7,48697,6,0,Canola Oil,13,pantry
2019709,550836,2,13,9.0,7,6825,7,0,Breakfast Veggie Bacon Strips,1,frozen
2019710,550836,2,13,9.0,7,44325,8,0,Elbow Macaroni Pasta,9,dry goods pasta
2019711,550836,2,13,9.0,7,23909,9,0,2% Reduced Fat Milk,16,dairy eggs
2019712,550836,2,13,9.0,7,4461,10,0,Organic Raw Unfiltered Apple Cider Vinegar,13,pantry

In [4]:
orders.columns

Index(['order_id', 'order_dow', 'order_hour_of_day', 'days_since_prior_order',
       'order_number', 'product_id', 'add_to_cart_order', 'reordered',
       'product_name', 'department_id', 'department'],
      dtype='str')

In [5]:
encoded = te.fit(transactions).transform(transactions)
basket = pd.DataFrame(
    encoded,
    columns=te.columns_
)

frequent_itemsets = apriori(
    basket,
    min_support=0.01,
    use_colnames=True
)

In [6]:
rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.15
)

In [7]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Organic Baby Spinach}),frozenset({Bag of Organic Bananas}),0.076390,0.117930,0.015930,0.208535,1.768296,1.0,0.006921,1.114478,0.470419,0.089299,0.102719,0.171808
1,frozenset({Bag of Organic Bananas}),frozenset({Organic Hass Avocado}),0.117930,0.066115,0.019120,0.162130,2.452243,1.0,0.011323,1.114594,0.671387,0.115931,0.102813,0.225662
2,frozenset({Organic Hass Avocado}),frozenset({Bag of Organic Bananas}),0.066115,0.117930,0.019120,0.289193,2.452243,1.0,0.011323,1.240942,0.634136,0.115931,0.194160,0.225662
3,frozenset({Organic Raspberries}),frozenset({Bag of Organic Bananas}),0.042400,0.117930,0.012635,0.297995,2.526883,1.0,0.007635,1.256502,0.631010,0.085548,0.204139,0.202568
4,frozenset({Bag of Organic Bananas}),frozenset({Organic Strawberries}),0.117930,0.082210,0.019355,0.164123,1.996385,1.0,0.009660,1.097996,0.565822,0.107061,0.089250,0.199778
5,frozenset({Organic Strawberries}),frozenset({Bag of Organic Bananas}),0.082210,0.117930,0.019355,0.235434,1.996385,1.0,0.009660,1.153687,0.543800,0.107061,0.133214,0.199778
6,frozenset({Large Lemon}),frozenset({Banana}),0.048465,0.147520,0.013355,0.275560,1.867948,1.0,0.006205,1.176743,0.488320,0.073126,0.150197,0.183045
7,frozenset({Limes}),frozenset({Banana}),0.044215,0.147520,0.010340,0.233857,1.585258,1.0,0.003817,1.112691,0.386267,0.057003,0.101278,0.151975
8,frozenset({Organic Avocado}),frozenset({Banana}),0.054870,0.147520,0.017260,0.314562,2.132333,1.0,0.009166,1.243701,0.561859,0.093232,0.195948,0.215781
9,frozenset({Organic Baby Spinach}),frozenset({Banana}),0.076390,0.147520,0.016185,0.211873,1.436234,1.0,0.004916,1.081653,0.328856,0.077916,0.075489,0.160794
10,frozenset({Organic Fuji Apple}),frozenset({Banana}),0.027945,0.147520,0.010735,0.384147,2.604036,1.0,0.006613,1.384227,0.633689,0.065167,0.277575,0.228459
11,frozenset({Organic Strawberries}),frozenset({Banana}),0.082210,0.147520,0.017370,0.211288,1.432268,1.0,0.005242,1.080851,0.328841,0.081795,0.074803,0.164517
12,frozenset({Organic Whole Milk}),frozenset({Banana}),0.043550,0.147520,0.010135,0.232721,1.577556,1.0,0.003711,1.111043,0.382778,0.056015,0.099945,0.150712
13,frozenset({Strawberries}),frozenset({Banana}),0.044480,0.147520,0.012830,0.288444,1.955289,1.0,0.006268,1.198051,0.511310,0.071608,0.165311,0.187708
14,frozenset({Organic Hass Avocado}),frozenset({Organic Baby Spinach}),0.066115,0.076390,0.010965,0.165847,2.171061,1.0,0.005914,1.107243,0.577583,0.083359,0.096856,0.154694
15,frozenset({Organic Baby Spinach}),frozenset({Organic Strawberries}),0.076390,0.082210,0.012430,0.162718,1.979292,1.0,0.006150,1.096154,0.535690,0.085038,0.087719,0.156958
16,frozenset({Organic Strawberries}),frozenset({Organic Baby Spinach}),0.082210,0.076390,0.012430,0.151198,1.979292,1.0,0.006150,1.088134,0.539087,0.085038,0.080995,0.156958
17,frozenset({Organic Hass Avocado}),frozenset({Organic Strawberries}),0.066115,0.082210,0.012580,0.190275,2.314494,1.0,0.007145,1.133458,0.608148,0.092674,0.117744,0.171649
18,frozenset({Organic Strawberries}),frozenset({Organic Hass Avocado}),0.082210,0.066115,0.012580,0.153023,2.314494,1.0,0.007145,1.102609,0.618813,0.092674,0.093060,0.171649
19,frozenset({Organic Raspberries}),frozenset({Organic Strawberries}),0.042400,0.082210,0.010510,0.247877,3.015173,1.0,0.007024,1.220266,0.697937,0.092112,0.180507,0.187860

In [8]:
rules.columns

Index(['antecedents', 'consequents', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift',
       'representativity', 'leverage', 'conviction', 'zhangs_metric',
       'jaccard', 'certainty', 'kulczynski'],
      dtype='str')

In [9]:
frequent_itemsets

      support                                           itemsets
0    0.011550                frozenset({100% Raw Coconut Water})
1    0.018920                frozenset({100% Whole Wheat Bread})
2    0.011250                   frozenset({2% Reduced Fat Milk})
3    0.026610              frozenset({Apple Honeycrisp Organic})
4    0.020865                             frozenset({Asparagus})
..        ...                                                ...
115  0.012830                  frozenset({Banana, Strawberries})
116  0.010965  frozenset({Organic Baby Spinach, Organic Hass ...
117  0.012430  frozenset({Organic Baby Spinach, Organic Straw...
118  0.012580  frozenset({Organic Hass Avocado, Organic Straw...
119  0.010510  frozenset({Organic Raspberries, Organic Strawb...

[120 rows x 2 columns]

In [10]:
print(frequent_itemsets.shape)
print(frequent_itemsets.head())

frequent_itemsets["size"] = (
    frequent_itemsets["itemsets"].apply(len)
)

print(
    frequent_itemsets["size"].value_counts()
)

(120, 2)
    support                               itemsets
0  0.011550    frozenset({100% Raw Coconut Water})
1  0.018920    frozenset({100% Whole Wheat Bread})
2  0.011250       frozenset({2% Reduced Fat Milk})
3  0.026610  frozenset({Apple Honeycrisp Organic})
4  0.020865                 frozenset({Asparagus})
size
1    104
2     16
Name: count, dtype: int64

In [11]:
print(type(rules['antecedents'][0]))
print(type(orders['product_name'][0]))

<class 'frozenset'>
<class 'str'>

In [12]:
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Organic Baby Spinach}),frozenset({Bag of Organic Bananas}),0.076390,0.117930,0.015930,0.208535,1.768296,1.0,0.006921,1.114478,0.470419,0.089299,0.102719,0.171808
1,frozenset({Bag of Organic Bananas}),frozenset({Organic Hass Avocado}),0.117930,0.066115,0.019120,0.162130,2.452243,1.0,0.011323,1.114594,0.671387,0.115931,0.102813,0.225662
2,frozenset({Organic Hass Avocado}),frozenset({Bag of Organic Bananas}),0.066115,0.117930,0.019120,0.289193,2.452243,1.0,0.011323,1.240942,0.634136,0.115931,0.194160,0.225662
3,frozenset({Organic Raspberries}),frozenset({Bag of Organic Bananas}),0.042400,0.117930,0.012635,0.297995,2.526883,1.0,0.007635,1.256502,0.631010,0.085548,0.204139,0.202568
4,frozenset({Bag of Organic Bananas}),frozenset({Organic Strawberries}),0.117930,0.082210,0.019355,0.164123,1.996385,1.0,0.009660,1.097996,0.565822,0.107061,0.089250,0.199778
5,frozenset({Organic Strawberries}),frozenset({Bag of Organic Bananas}),0.082210,0.117930,0.019355,0.235434,1.996385,1.0,0.009660,1.153687,0.543800,0.107061,0.133214,0.199778
6,frozenset({Large Lemon}),frozenset({Banana}),0.048465,0.147520,0.013355,0.275560,1.867948,1.0,0.006205,1.176743,0.488320,0.073126,0.150197,0.183045
7,frozenset({Limes}),frozenset({Banana}),0.044215,0.147520,0.010340,0.233857,1.585258,1.0,0.003817,1.112691,0.386267,0.057003,0.101278,0.151975
8,frozenset({Organic Avocado}),frozenset({Banana}),0.054870,0.147520,0.017260,0.314562,2.132333,1.0,0.009166,1.243701,0.561859,0.093232,0.195948,0.215781
9,frozenset({Organic Baby Spinach}),frozenset({Banana}),0.076390,0.147520,0.016185,0.211873,1.436234,1.0,0.004916,1.081653,0.328856,0.077916,0.075489,0.160794

In [13]:
rules.columns

Index(['antecedents', 'consequents', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift',
       'representativity', 'leverage', 'conviction', 'zhangs_metric',
       'jaccard', 'certainty', 'kulczynski'],
      dtype='str')

In [14]:
print(type(rules))
print(rules[['antecedents', 'consequents']].head(10))

<class 'pandas.DataFrame'>
                           antecedents                          consequents
0    frozenset({Organic Baby Spinach})  frozenset({Bag of Organic Bananas})
1  frozenset({Bag of Organic Bananas})    frozenset({Organic Hass Avocado})
2    frozenset({Organic Hass Avocado})  frozenset({Bag of Organic Bananas})
3     frozenset({Organic Raspberries})  frozenset({Bag of Organic Bananas})
4  frozenset({Bag of Organic Bananas})    frozenset({Organic Strawberries})
5    frozenset({Organic Strawberries})  frozenset({Bag of Organic Bananas})
6             frozenset({Large Lemon})                  frozenset({Banana})
7                   frozenset({Limes})                  frozenset({Banana})
8         frozenset({Organic Avocado})                  frozenset({Banana})
9    frozenset({Organic Baby Spinach})                  frozenset({Banana})

In [15]:
association_df = rules[['antecedents', 'consequents', 'antecedent support', 'consequent support', 
                        'support', 'confidence','lift']]

In [16]:
# association_df['antecedents_list'] = association_df['antecedents'].apply(list)
# association_df['consequents_list'] = association_df['consequents'].apply(list)

In [17]:
association_df['antecedents_list'] = association_df['antecedents'].apply(
    lambda x: next(iter(x))
)

association_df['consequents_list'] = association_df['consequents'].apply(
    lambda x: next(iter(x))
)

In [18]:
print(type(association_df['antecedents_list'][0]))
print(association_df['antecedents_list'][0])

<class 'str'>
Organic Baby Spinach

In [19]:
final_dataset = pd.merge(orders, association_df, left_on='product_name', right_on='antecedents_list', how='inner')

In [20]:
final_dataset.columns

Index(['order_id', 'order_dow', 'order_hour_of_day', 'days_since_prior_order',
       'order_number', 'product_id', 'add_to_cart_order', 'reordered',
       'product_name', 'department_id', 'department', 'antecedents',
       'consequents', 'antecedent support', 'consequent support', 'support',
       'confidence', 'lift', 'antecedents_list', 'consequents_list'],
      dtype='str')

In [21]:
final_dataset.sort_values(by=['order_id', 'add_to_cart_order'])

,order_id,order_dow,order_hour_of_day,days_since_prior_order,order_number,product_id,add_to_cart_order,reordered,product_name,department_id,department,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,antecedents_list,consequents_list
168482,27,6,20,14.0,16,13176,1,1,Bag of Organic Bananas,4,produce,frozenset({Bag of Organic Bananas}),frozenset({Organic Hass Avocado}),0.11793,0.066115,0.019120,0.162130,2.452243,Bag of Organic Bananas,Organic Hass Avocado
168483,27,6,20,14.0,16,13176,1,1,Bag of Organic Bananas,4,produce,frozenset({Bag of Organic Bananas}),frozenset({Organic Strawberries}),0.11793,0.082210,0.019355,0.164123,1.996385,Bag of Organic Bananas,Organic Strawberries
168484,27,6,20,14.0,16,47766,7,1,Organic Avocado,4,produce,frozenset({Organic Avocado}),frozenset({Banana}),0.05487,0.147520,0.017260,0.314562,2.132333,Organic Avocado,Banana
262261,31,6,15,14.0,7,21903,3,1,Organic Baby Spinach,4,produce,frozenset({Organic Baby Spinach}),frozenset({Bag of Organic Bananas}),0.07639,0.117930,0.015930,0.208535,1.768296,Organic Baby Spinach,Bag of Organic Bananas
262262,31,6,15,14.0,7,21903,3,1,Organic Baby Spinach,4,produce,frozenset({Organic Baby Spinach}),frozenset({Banana}),0.07639,0.147520,0.016185,0.211873,1.436234,Organic Baby Spinach,Banana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97999,3421002,2,16,28.0,6,13176,3,1,Bag of Organic Bananas,4,produce,frozenset({Bag of Organic Bananas}),frozenset({Organic Strawberries}),0.11793,0.082210,0.019355,0.164123,1.996385,Bag of Organic Bananas,Organic Strawberries
10221,3421007,0,12,7.0,14,47766,1,1,Organic Avocado,4,produce,frozenset({Organic Avocado}),frozenset({Banana}),0.05487,0.147520,0.017260,0.314562,2.132333,Organic Avocado,Banana
9108,3421068,4,16,15.0,2,16797,1,0,Strawberries,4,produce,frozenset({Strawberries}),frozenset({Banana}),0.04448,0.147520,0.012830,0.288444,1.955289,Strawberries,Banana
9109,3421068,4,16,15.0,2,13176,2,1,Bag of Organic Bananas,4,produce,frozenset({Bag of Organic Bananas}),frozenset({Organic Hass Avocado}),0.11793,0.066115,0.019120,0.162130,2.452243,Bag of Organic Bananas,Organic Hass Avocado
9110,3421068,4,16,15.0,2,13176,2,1,Bag of Organic Bananas,4,produce,frozenset({Bag of Organic Bananas}),frozenset({Organic Strawberries}),0.11793,0.082210,0.019355,0.164123,1.996385,Bag of Organic Bananas,Organic Strawberries

In [22]:
orders[
    orders["order_id"] == 27
][[
    "order_id",
    "product_id",
    "product_name",
    "add_to_cart_order"
]].sort_values("add_to_cart_order")

,order_id,product_id,product_name,add_to_cart_order
1267001,27,13176,Bag of Organic Bananas,1
1267002,27,30442,Low Fat Vanilla Yogurt,2
1267003,27,13646,Lemon Hummus,3
1267004,27,21019,Roasted Red Pepper Hummus,4
1267005,27,38226,Dark Chocolate Chips,5
1267006,27,18479,Organic Low Sodium Vegetable Broth,6
1267007,27,47766,Organic Avocado,7
1267008,27,17794,Carrots,8
1267009,27,42701,Organic Sour Cream,9
1267010,27,21938,Green Bell Pepper,10
1267011,27,5373,Organic No Salt Added Diced Tomatoes,11
1267012,27,28849,No Salt Added Black Beans,12
1267013,27,41588,Firm Tofu,13
1267014,27,3382,Organic Eggplant,14
1267015,27,19478,Organic Marinara Pasta Sauce,15
1267016,27,28985,Michigan Organic Kale,16
1267017,27,49383,Organic Bunch Beets,17
1267018,27,40604,Feta Cheese Crumbles,18
1267019,27,8654,Pasta Joy Ready Organic Brown Rice Pasta Penne,19
1267020,27,2447,3 lb Clementines,20
1267021,27,24489,Organic Whole Strawberries,21
1267022,27,26128,Organic Mango Chunks,22
1267023,27,15527,Teriyaki Veggie Burgers,23
1267024,27,41950,Organic Tomato Cluster,24
1267025,27,20638,Coconut Sugar Pure & Unrefined,25
1267026,27,27451,Almond Meal/Flour,26
1267027,27,10243,Parchment Paper,27

In [23]:
final_dataset[
    final_dataset["order_id"] == 27
][[
    "order_id",
    "product_id",
    "product_name",
    "add_to_cart_order",
    "antecedents_list",
    "consequents_list",
    "lift"
]].sort_values("add_to_cart_order")

,order_id,product_id,product_name,add_to_cart_order,antecedents_list,consequents_list,lift
168482,27,13176,Bag of Organic Bananas,1,Bag of Organic Bananas,Organic Hass Avocado,2.452243
168483,27,13176,Bag of Organic Bananas,1,Bag of Organic Bananas,Organic Strawberries,1.996385
168484,27,47766,Organic Avocado,7,Organic Avocado,Banana,2.132333

In [24]:
actual_products = orders[["order_id", "product_id", "product_name", "add_to_cart_order"]].copy()

actual_products = actual_products.rename(
    columns={
        "product_id": "actual_product_id",
        "product_name": "actual_product_name",
        "add_to_cart_order": "actual_add_to_cart_order"})

actual_products[actual_products['order_id'] == 27]

,order_id,actual_product_id,actual_product_name,actual_add_to_cart_order
1267001,27,13176,Bag of Organic Bananas,1
1267002,27,30442,Low Fat Vanilla Yogurt,2
1267003,27,13646,Lemon Hummus,3
1267004,27,21019,Roasted Red Pepper Hummus,4
1267005,27,38226,Dark Chocolate Chips,5
1267006,27,18479,Organic Low Sodium Vegetable Broth,6
1267007,27,47766,Organic Avocado,7
1267008,27,17794,Carrots,8
1267009,27,42701,Organic Sour Cream,9
1267010,27,21938,Green Bell Pepper,10
1267011,27,5373,Organic No Salt Added Diced Tomatoes,11
1267012,27,28849,No Salt Added Black Beans,12
1267013,27,41588,Firm Tofu,13
1267014,27,3382,Organic Eggplant,14
1267015,27,19478,Organic Marinara Pasta Sauce,15
1267016,27,28985,Michigan Organic Kale,16
1267017,27,49383,Organic Bunch Beets,17
1267018,27,40604,Feta Cheese Crumbles,18
1267019,27,8654,Pasta Joy Ready Organic Brown Rice Pasta Penne,19
1267020,27,2447,3 lb Clementines,20
1267021,27,24489,Organic Whole Strawberries,21
1267022,27,26128,Organic Mango Chunks,22
1267023,27,15527,Teriyaki Veggie Burgers,23
1267024,27,41950,Organic Tomato Cluster,24
1267025,27,20638,Coconut Sugar Pure & Unrefined,25
1267026,27,27451,Almond Meal/Flour,26
1267027,27,10243,Parchment Paper,27

In [25]:
print(final_dataset.shape)
print(orders.shape)

(268108, 20)
(2019713, 11)

In [26]:
model_df = pd.merge(final_dataset, actual_products, left_on=["order_id", "consequents_list"] ,right_on=["order_id", "actual_product_name"],how="left")
model_df[model_df['order_id'] == 27]

,order_id,order_dow,order_hour_of_day,days_since_prior_order,order_number,product_id,add_to_cart_order,reordered,product_name,department_id,...,antecedent support,consequent support,support,confidence,lift,antecedents_list,consequents_list,actual_product_id,actual_product_name,actual_add_to_cart_order
168482,27,6,20,14.0,16,13176,1,1,Bag of Organic Bananas,4,...,0.11793,0.066115,0.019120,0.162130,2.452243,Bag of Organic Bananas,Organic Hass Avocado,NaN,NaN,NaN
168483,27,6,20,14.0,16,13176,1,1,Bag of Organic Bananas,4,...,0.11793,0.082210,0.019355,0.164123,1.996385,Bag of Organic Bananas,Organic Strawberries,NaN,NaN,NaN
168484,27,6,20,14.0,16,47766,7,1,Organic Avocado,4,...,0.05487,0.147520,0.017260,0.314562,2.132333,Organic Avocado,Banana,NaN,NaN,NaN

In [27]:
model_df[['actual_product_id', 'actual_product_name',	'actual_add_to_cart_order']].sample(50)

        actual_product_id     actual_product_name  actual_add_to_cart_order
216810                NaN                     NaN                       NaN
206562                NaN                     NaN                       NaN
131735                NaN                     NaN                       NaN
7787              24852.0                  Banana                       9.0
11295                 NaN                     NaN                       NaN
100314                NaN                     NaN                       NaN
106125                NaN                     NaN                       NaN
77232                 NaN                     NaN                       NaN
61841                 NaN                     NaN                       NaN
144042                NaN                     NaN                       NaN
255547                NaN                     NaN                       NaN
191025                NaN                     NaN                       NaN
67053             24852.0                  Banana                       3.0
112802                NaN                     NaN                       NaN
260468                NaN                     NaN                       NaN
21204                 NaN                     NaN                       NaN
185806                NaN                     NaN                       NaN
10977                 NaN                     NaN                       NaN
117911                NaN                     NaN                       NaN
97018                 NaN                     NaN                       NaN
98398                 NaN                     NaN                       NaN
245412            13176.0  Bag of Organic Bananas                       4.0
71634                 NaN                     NaN                       NaN
4379                  NaN                     NaN                       NaN
41301                 NaN                     NaN                       NaN
149073                NaN                     NaN                       NaN
114183            47209.0    Organic Hass Avocado                       8.0
118694                NaN                     NaN                       NaN
262782                NaN                     NaN                       NaN
195004                NaN                     NaN                       NaN
191029                NaN                     NaN                       NaN
221370            24852.0                  Banana                       1.0
267469                NaN                     NaN                       NaN
42127                 NaN                     NaN                       NaN
128507                NaN                     NaN                       NaN
105927                NaN                     NaN                       NaN
103630                NaN                     NaN                       NaN
265880                NaN                     NaN                       NaN
70357                 NaN                     NaN                       NaN
180960                NaN                     NaN                       NaN
116827            21903.0    Organic Baby Spinach                      11.0
173772                NaN                     NaN                       NaN
108965                NaN                     NaN                       NaN
197318                NaN                     NaN                       NaN
6828                  NaN                     NaN                       NaN
138712                NaN                     NaN                       NaN
8894                  NaN                     NaN                       NaN
90200                 NaN                     NaN                       NaN
239759                NaN                     NaN                       NaN
245744                NaN                     NaN                       NaN

In [28]:
import numpy as np
model_df["label"] = (model_df["actual_add_to_cart_order"] > model_df["add_to_cart_order"]).astype(int)
model_df["candidate_purchased"] = np.where(model_df["label"] == 1, "Yes", "No")

In [29]:
model_df

,order_id,order_dow,order_hour_of_day,days_since_prior_order,order_number,product_id,add_to_cart_order,reordered,product_name,department_id,...,support,confidence,lift,antecedents_list,consequents_list,actual_product_id,actual_product_name,actual_add_to_cart_order,label,candidate_purchased
0,1901567,1,10,3.0,3,47766,1,1,Organic Avocado,4,...,0.017260,0.314562,2.132333,Organic Avocado,Banana,NaN,NaN,NaN,0,No
1,1972919,0,16,7.0,6,47766,4,1,Organic Avocado,4,...,0.017260,0.314562,2.132333,Organic Avocado,Banana,NaN,NaN,NaN,0,No
2,3321109,5,18,3.0,5,21137,3,1,Organic Strawberries,4,...,0.019355,0.235434,1.996385,Organic Strawberries,Bag of Organic Bananas,NaN,NaN,NaN,0,No
3,3321109,5,18,3.0,5,21137,3,1,Organic Strawberries,4,...,0.017370,0.211288,1.432268,Organic Strawberries,Banana,NaN,NaN,NaN,0,No
4,3321109,5,18,3.0,5,21137,3,1,Organic Strawberries,4,...,0.012430,0.151198,1.979292,Organic Strawberries,Organic Baby Spinach,NaN,NaN,NaN,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268103,3356245,5,9,10.0,40,27845,3,1,Organic Whole Milk,16,...,0.010135,0.232721,1.577556,Organic Whole Milk,Banana,NaN,NaN,NaN,0,No
268104,3356245,5,9,10.0,40,27966,7,1,Organic Raspberries,4,...,0.012635,0.297995,2.526883,Organic Raspberries,Bag of Organic Bananas,13176.0,Bag of Organic Bananas,8.0,1,Yes
268105,3356245,5,9,10.0,40,27966,7,1,Organic Raspberries,4,...,0.010510,0.247877,3.015173,Organic Raspberries,Organic Strawberries,NaN,NaN,NaN,0,No
268106,3356245,5,9,10.0,40,13176,8,1,Bag of Organic Bananas,4,...,0.019120,0.162130,2.452243,Bag of Organic Bananas,Organic Hass Avocado,NaN,NaN,NaN,0,No
268107,3356245,5,9,10.0,40,13176,8,1,Bag of Organic Bananas,4,...,0.019355,0.164123,1.996385,Bag of Organic Bananas,Organic Strawberries,NaN,NaN,NaN,0,No

In [30]:
model_df["label"].value_counts(normalize=True)

label
0    0.909954
1    0.090046
Name: proportion, dtype: float64

In [31]:
order_stats = (
    model_df
    .groupby("order_id")["label"]
    .agg(
        candidates="count",
        positives="sum"
    )
)

print(order_stats.describe())

         candidates     positives
count  83399.000000  83399.000000
mean       3.214763      0.289476
std        2.224774      0.681165
min        1.000000      0.000000
25%        1.000000      0.000000
50%        3.000000      0.000000
75%        4.000000      0.000000
max       16.000000      8.000000

In [32]:
print(
    (order_stats["positives"] > 0).mean()
)

0.20847971798223

In [33]:
model_df.columns

Index(['order_id', 'order_dow', 'order_hour_of_day', 'days_since_prior_order',
       'order_number', 'product_id', 'add_to_cart_order', 'reordered',
       'product_name', 'department_id', 'department', 'antecedents',
       'consequents', 'antecedent support', 'consequent support', 'support',
       'confidence', 'lift', 'antecedents_list', 'consequents_list',
       'actual_product_id', 'actual_product_name', 'actual_add_to_cart_order',
       'label', 'candidate_purchased'],
      dtype='str')

In [34]:
product_t = model_df[
    ["product_name", "product_id", "department_id", "department"]
].drop_duplicates("product_id").copy()

In [35]:
product_t = product_t.rename(
    columns={
        "product_id": "recommended_product_id",
        "product_name": "recommended_product_name",
        "department_id": "recommended_department_id",
        "department": "recommended_department_name"
    }
)

In [36]:
ml_data = model_df.merge(
    product_t,
    left_on="consequents_list",
    right_on="recommended_product_name",
    how="left",
    validate="many_to_one"
)

In [37]:
ml_data.columns

Index(['order_id', 'order_dow', 'order_hour_of_day', 'days_since_prior_order',
       'order_number', 'product_id', 'add_to_cart_order', 'reordered',
       'product_name', 'department_id', 'department', 'antecedents',
       'consequents', 'antecedent support', 'consequent support', 'support',
       'confidence', 'lift', 'antecedents_list', 'consequents_list',
       'actual_product_id', 'actual_product_name', 'actual_add_to_cart_order',
       'label', 'candidate_purchased', 'recommended_product_name',
       'recommended_product_id', 'recommended_department_id',
       'recommended_department_name'],
      dtype='str')

In [38]:
final_ml_model_data = ml_data[
    [
        "order_id",
        "order_dow",
        "order_hour_of_day",
        "days_since_prior_order",
        "order_number",
        "add_to_cart_order",
        "reordered",
        "product_id",
        "product_name",
        "consequents_list",
        "support",
        "confidence",
        "lift",
        "label",
        "recommended_product_id",
        "recommended_product_name",
        "recommended_department_id",
        "recommended_department_name"
    ]
].copy()

In [39]:
final_ml_model_data = final_ml_model_data.rename(
    columns={
        "product_id": "trigger_product_id",
        "product_name": "trigger_product_name",
        "consequents_list": "recommended_product_name",
        "add_to_cart_order": "cart_size"
    }
)

In [41]:
final_ml_model_data

,order_id,order_dow,order_hour_of_day,days_since_prior_order,order_number,cart_size,reordered,trigger_product_id,trigger_product_name,recommended_product_name,support,confidence,lift,label,recommended_product_id,recommended_product_name,recommended_department_id,recommended_department_name
0,1901567,1,10,3.0,3,1,1,47766,Organic Avocado,Banana,0.017260,0.314562,2.132333,0,NaN,NaN,NaN,NaN
1,1972919,0,16,7.0,6,4,1,47766,Organic Avocado,Banana,0.017260,0.314562,2.132333,0,NaN,NaN,NaN,NaN
2,3321109,5,18,3.0,5,3,1,21137,Organic Strawberries,Bag of Organic Bananas,0.019355,0.235434,1.996385,0,13176.0,Bag of Organic Bananas,4.0,produce
3,3321109,5,18,3.0,5,3,1,21137,Organic Strawberries,Banana,0.017370,0.211288,1.432268,0,NaN,NaN,NaN,NaN
4,3321109,5,18,3.0,5,3,1,21137,Organic Strawberries,Organic Baby Spinach,0.012430,0.151198,1.979292,0,21903.0,Organic Baby Spinach,4.0,produce
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268103,3356245,5,9,10.0,40,3,1,27845,Organic Whole Milk,Banana,0.010135,0.232721,1.577556,0,NaN,NaN,NaN,NaN
268104,3356245,5,9,10.0,40,7,1,27966,Organic Raspberries,Bag of Organic Bananas,0.012635,0.297995,2.526883,1,13176.0,Bag of Organic Bananas,4.0,produce
268105,3356245,5,9,10.0,40,7,1,27966,Organic Raspberries,Organic Strawberries,0.010510,0.247877,3.015173,0,21137.0,Organic Strawberries,4.0,produce
268106,3356245,5,9,10.0,40,8,1,13176,Bag of Organic Bananas,Organic Hass Avocado,0.019120,0.162130,2.452243,0,47209.0,Organic Hass Avocado,4.0,produce
268107,3356245,5,9,10.0,40,8,1,13176,Bag of Organic Bananas,Organic Strawberries,0.019355,0.164123,1.996385,0,21137.0,Organic Strawberries,4.0,produce

In [42]:
print(type(final_ml_model_data))

<class 'pandas.DataFrame'>

In [44]:
def ml_model_data_preparation(orders_data):

    association_df = rules[['antecedents', 
                                  'consequents', 
                                  'support', 
                                  'confidence',
                                  'lift']]
    
    # data conversion from frozen set to list for merging
    association_df['antecedents_list'] = association_df['antecedents'].apply(lambda x: next(iter(x)))
    association_df['consequents_list'] = association_df['consequents'].apply(lambda x: next(iter(x)))

    final_dataset = pd.merge(orders, association_df, 
                            left_on='product_name', 
                            right_on='antecedents_list', 
                            how='inner')

    # validation columns for history purchase and base layer recommendation matching
    actual_products = orders_data[["order_id", 
                              "product_name", 
                              "add_to_cart_order"]].copy()

    actual_products = actual_products.rename(columns={"product_name": "actual_product_name",
                                                      "add_to_cart_order": "actual_add_to_cart_order"})

    model_df = pd.merge(final_dataset, 
                        actual_products, 
                        left_on=["order_id", "consequents_list"],
                        right_on=["order_id", "actual_product_name"],
                        how="left")

    # lable for the final ml_data based on base layer recommendation and purchase history [target column]
    model_df["label"] = (model_df["actual_add_to_cart_order"] > model_df["add_to_cart_order"]).astype(int)

    # extra table for product restructuring 
    product_t = orders[[  "product_name", 
                          "product_id", 
                          "department_id", 
                          "department"]].drop_duplicates("product_id").copy()

    product_t = product_t.rename(
        columns={
            "product_id": "recommended_product_id",
            "product_name": "recommended_product_name",
            "department_id": "recommended_department_id",
            "department": "recommended_department_name"
        }
    )

    ml_data = model_df.merge(
        product_t,
        left_on="consequents_list",
        right_on="recommended_product_name",
        how="left",
        validate="many_to_one"
    )

    # Final ml_dataset_output for ml csv
    final_ml_model_data = ml_data[
        [
            "order_id",
            "order_dow",
            "order_hour_of_day",
            "days_since_prior_order",
            "order_number",
            "add_to_cart_order",
            "product_id",
            "product_name",
            "consequents_list",
            "reordered",
            "recommended_product_id",
            "recommended_product_name",
            "recommended_department_id",
            "recommended_department_name",
            "support",
            "confidence",
            "lift",
            "label"
        ]
    ].copy()

    final_ml_model_data = final_ml_model_data.rename(
        columns={
            "product_id": "trigger_product_id",
            "product_name": "trigger_product_name",
            "add_to_cart_order": "cart_size",
            "reordered" : "trigger_reordered"
        }
    )

    return final_ml_model_data
    print(final_ml_model_data.head())

In [45]:
ml_model_data_preparation(orders)

,order_id,order_dow,order_hour_of_day,days_since_prior_order,order_number,cart_size,trigger_product_id,trigger_product_name,consequents_list,trigger_reordered,recommended_product_id,recommended_product_name,recommended_department_id,recommended_department_name,support,confidence,lift,label
0,1901567,1,10,3.0,3,1,47766,Organic Avocado,Banana,1,24852,Banana,4,produce,0.017260,0.314562,2.132333,0
1,1972919,0,16,7.0,6,4,47766,Organic Avocado,Banana,1,24852,Banana,4,produce,0.017260,0.314562,2.132333,0
2,3321109,5,18,3.0,5,3,21137,Organic Strawberries,Bag of Organic Bananas,1,13176,Bag of Organic Bananas,4,produce,0.019355,0.235434,1.996385,0
3,3321109,5,18,3.0,5,3,21137,Organic Strawberries,Banana,1,24852,Banana,4,produce,0.017370,0.211288,1.432268,0
4,3321109,5,18,3.0,5,3,21137,Organic Strawberries,Organic Baby Spinach,1,21903,Organic Baby Spinach,4,produce,0.012430,0.151198,1.979292,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268103,3356245,5,9,10.0,40,3,27845,Organic Whole Milk,Banana,1,24852,Banana,4,produce,0.010135,0.232721,1.577556,0
268104,3356245,5,9,10.0,40,7,27966,Organic Raspberries,Bag of Organic Bananas,1,13176,Bag of Organic Bananas,4,produce,0.012635,0.297995,2.526883,1
268105,3356245,5,9,10.0,40,7,27966,Organic Raspberries,Organic Strawberries,1,21137,Organic Strawberries,4,produce,0.010510,0.247877,3.015173,0
268106,3356245,5,9,10.0,40,8,13176,Bag of Organic Bananas,Organic Hass Avocado,1,47209,Organic Hass Avocado,4,produce,0.019120,0.162130,2.452243,0
268107,3356245,5,9,10.0,40,8,13176,Bag of Organic Bananas,Organic Strawberries,1,21137,Organic Strawberries,4,produce,0.019355,0.164123,1.996385,0