In [1]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()

In [2]:
import pandas as pd 
orders = pd.read_csv("/Users/abhijeetsinghparihar/Desktop/Projects/Supply Chain Project/CartIQ/data/processed/master_orders.csv")

In [3]:
transactions = (orders.groupby("order_id")["product_name"].apply(list).tolist())
print(type(transactions))
print(transactions[0])

<class 'list'>
['Organic Red Radish, Bunch', 'Whole White Mushrooms', 'Baby Spinach', 'Low Fat Kefir Cultured Milk Smoothie Lowfat Probiotic Blueberry', 'Snak-Saks Crackers', 'Natural Applesauce Snack & Go Pouches', 'Green Beans', 'Extra Virgin Olive Oil', 'Distilled Water', 'French Baguettes, Take & Bake, Twin Pack', 'Organic Bread with 21 Whole Grains', '100% Apple Juice Original', 'Vanilla Almond Breeze Almond Milk', 'Natural Sharp Cheddar Sliced Cheese', 'Fruit & Nutty Almonds Raisins Cranberries Pecans Granola']

In [4]:
encoded = te.fit(transactions).transform(transactions)
basket = pd.DataFrame(
    encoded,
    columns=te.columns_
)

In [5]:
basket.columns.size

40649

In [6]:
orders['product_name'].nunique()

40649

In [7]:
orders['order_id'].nunique()

200000

In [8]:
print(f"\nThe total number of order are {basket.shape[0]}")

The total number of order are 200000

In [9]:
basket.shape

(200000, 40649)

In [10]:
basket

,#2 Coffee Filters,#2 Cone White Coffee Filters,#4 Natural Brown Coffee Filters,& Go! Hazelnut Spread + Pretzel Sticks,(70% Juice!) Mountain Raspberry Juice Squeeze,0 Calorie Acai Raspberry Water Beverage,0 Calorie Fuji Apple Pear Water Beverage,0 Calorie Strawberry Dragonfruit Water Beverage,0% Fat Black Cherry Greek Yogurt y,0% Fat Blueberry Greek Yogurt,...,with Seasoned Roasted Potatoes Scrambled Eggs & Sausage,with Sweet & Smoky BBQ Sauce Cheeseburger Sliders,with Sweet Cinnamon Bunches Cereal,with Xylitol Cinnamon 18 Sticks Sugar Free Gum,with Xylitol Island Berry Lime 18 Sticks Sugar Free Gum,with Xylitol Original Flavor 18 Sticks Sugar Free Gum,with Xylitol Unwrapped Spearmint 50 Sticks Sugar Free Gum,with Xylitol Watermelon Twist 18 Sticks Sugar Free Gum,with a Splash of Mango Coconut Water,with a Splash of Pineapple Coconut Water
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
199996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
199997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
199998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
199999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(
    basket,
    min_support=0.01,
    use_colnames=True
)

      support                                           itemsets
0    0.011550                frozenset({100% Raw Coconut Water})
1    0.018920                frozenset({100% Whole Wheat Bread})
2    0.011250                   frozenset({2% Reduced Fat Milk})
3    0.026610              frozenset({Apple Honeycrisp Organic})
4    0.020865                             frozenset({Asparagus})
..        ...                                                ...
115  0.012830                  frozenset({Strawberries, Banana})
116  0.010965  frozenset({Organic Baby Spinach, Organic Hass ...
117  0.012430  frozenset({Organic Baby Spinach, Organic Straw...
118  0.012580  frozenset({Organic Hass Avocado, Organic Straw...
119  0.010510  frozenset({Organic Raspberries, Organic Strawb...

[120 rows x 2 columns]

In [17]:
frequent_itemsets

      support                                           itemsets
0    0.011550                frozenset({100% Raw Coconut Water})
1    0.018920                frozenset({100% Whole Wheat Bread})
2    0.011250                   frozenset({2% Reduced Fat Milk})
3    0.026610              frozenset({Apple Honeycrisp Organic})
4    0.020865                             frozenset({Asparagus})
..        ...                                                ...
115  0.012830                  frozenset({Strawberries, Banana})
116  0.010965  frozenset({Organic Baby Spinach, Organic Hass ...
117  0.012430  frozenset({Organic Baby Spinach, Organic Straw...
118  0.012580  frozenset({Organic Hass Avocado, Organic Straw...
119  0.010510  frozenset({Organic Raspberries, Organic Strawb...

[120 rows x 2 columns]

In [12]:
print(type(frequent_itemsets))

<class 'pandas.DataFrame'>

In [13]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.2
)

rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Organic Baby Spinach}),frozenset({Bag of Organic Bananas}),0.076390,0.11793,0.015930,0.208535,1.768296,1.0,0.006921,1.114478,0.470419,0.089299,0.102719,0.171808
1,frozenset({Organic Hass Avocado}),frozenset({Bag of Organic Bananas}),0.066115,0.11793,0.019120,0.289193,2.452243,1.0,0.011323,1.240942,0.634136,0.115931,0.194160,0.225662
2,frozenset({Organic Raspberries}),frozenset({Bag of Organic Bananas}),0.042400,0.11793,0.012635,0.297995,2.526883,1.0,0.007635,1.256502,0.631010,0.085548,0.204139,0.202568
3,frozenset({Organic Strawberries}),frozenset({Bag of Organic Bananas}),0.082210,0.11793,0.019355,0.235434,1.996385,1.0,0.009660,1.153687,0.543800,0.107061,0.133214,0.199778
4,frozenset({Large Lemon}),frozenset({Banana}),0.048465,0.14752,0.013355,0.275560,1.867948,1.0,0.006205,1.176743,0.488320,0.073126,0.150197,0.183045
5,frozenset({Limes}),frozenset({Banana}),0.044215,0.14752,0.010340,0.233857,1.585258,1.0,0.003817,1.112691,0.386267,0.057003,0.101278,0.151975
6,frozenset({Organic Avocado}),frozenset({Banana}),0.054870,0.14752,0.017260,0.314562,2.132333,1.0,0.009166,1.243701,0.561859,0.093232,0.195948,0.215781
7,frozenset({Organic Baby Spinach}),frozenset({Banana}),0.076390,0.14752,0.016185,0.211873,1.436234,1.0,0.004916,1.081653,0.328856,0.077916,0.075489,0.160794
8,frozenset({Organic Fuji Apple}),frozenset({Banana}),0.027945,0.14752,0.010735,0.384147,2.604036,1.0,0.006613,1.384227,0.633689,0.065167,0.277575,0.228459
9,frozenset({Organic Strawberries}),frozenset({Banana}),0.082210,0.14752,0.017370,0.211288,1.432268,1.0,0.005242,1.080851,0.328841,0.081795,0.074803,0.164517
10,frozenset({Organic Whole Milk}),frozenset({Banana}),0.043550,0.14752,0.010135,0.232721,1.577556,1.0,0.003711,1.111043,0.382778,0.056015,0.099945,0.150712
11,frozenset({Strawberries}),frozenset({Banana}),0.044480,0.14752,0.012830,0.288444,1.955289,1.0,0.006268,1.198051,0.511310,0.071608,0.165311,0.187708
12,frozenset({Organic Raspberries}),frozenset({Organic Strawberries}),0.042400,0.08221,0.010510,0.247877,3.015173,1.0,0.007024,1.220266,0.697937,0.092112,0.180507,0.187860

In [14]:
print(type(rules))

<class 'pandas.DataFrame'>

In [15]:
rules.shape

(13, 14)

In [16]:
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Organic Baby Spinach}),frozenset({Bag of Organic Bananas}),0.076390,0.11793,0.015930,0.208535,1.768296,1.0,0.006921,1.114478,0.470419,0.089299,0.102719,0.171808
1,frozenset({Organic Hass Avocado}),frozenset({Bag of Organic Bananas}),0.066115,0.11793,0.019120,0.289193,2.452243,1.0,0.011323,1.240942,0.634136,0.115931,0.194160,0.225662
2,frozenset({Organic Raspberries}),frozenset({Bag of Organic Bananas}),0.042400,0.11793,0.012635,0.297995,2.526883,1.0,0.007635,1.256502,0.631010,0.085548,0.204139,0.202568
3,frozenset({Organic Strawberries}),frozenset({Bag of Organic Bananas}),0.082210,0.11793,0.019355,0.235434,1.996385,1.0,0.009660,1.153687,0.543800,0.107061,0.133214,0.199778
4,frozenset({Large Lemon}),frozenset({Banana}),0.048465,0.14752,0.013355,0.275560,1.867948,1.0,0.006205,1.176743,0.488320,0.073126,0.150197,0.183045